"""
NRL Live Ladder API — Flattening Config
Source : api/NRL/liveLadder/{competitionId}/{seasonId}
         (XML root: LadderBySeason — same structure as ladder, with extra odds columns)
Bronze : L0 mode — l0payload holds each ladderposition's flat attributes
         (including live odds: premiershipOdds, top4Odds, top8Odds, etc.),
         payload holds the recentFormList data as numbered structs.

Output tables (target_prefix = nrl_datalakehouse_prd.bronze_stats_flatten):
  nrl_live_ladder_ladderposition          ← one row per team  (all ladder + odds stats)
  nrl_live_ladder_ladderposition_recent_form  ← one row per (team, form_entry)
                                               generated by post_run_fn below
"""

import json as _json
from functools import reduce


def _create_recent_form_table(config, spark):
    """
    Post-processing hook: convert numbered recentFormN struct fields in the
    bronze payload column into a proper Delta child table.

    Bronze payload shape  : [{"recentForm1": {"_text": "W"}, "recentForm2": ...}]
    Output table shape    : (team_id, form_order INT, result STRING,
                             ingested_at TIMESTAMP, ingested_from STRING)
    """
    from pyspark.sql import functions as F
    from pyspark.sql.window import Window

    bronze_table  = config["bronze_table"]
    target_prefix = config["target_prefix"]
    l1_element    = list(config["elements"].keys())[0]   # "ladderposition"
    target_table  = f"{target_prefix}_{l1_element}_recent_form"

    df = spark.table(bronze_table)

    # ── Detect max recentFormN index from one sample row ──────────────────
    sample_row = (
        df.select(F.col("payload").cast("string").alias("p"))
          .limit(1).collect()
    )
    if not sample_row or not sample_row[0]["p"]:
        print(f"[recent_form] Empty payload — skipping {target_table}")
        return

    payload_obj = _json.loads(sample_row[0]["p"])
    if isinstance(payload_obj, list) and payload_obj:
        payload_obj = payload_obj[0]

    max_n = max(
        (int(k[len("recentForm"):])
         for k in payload_obj.keys()
         if k.startswith("recentForm") and k[len("recentForm"):].isdigit()),
        default=0,
    )

    if max_n == 0:
        print(f"[recent_form] No recentFormN keys found in payload — skipping {target_table}")
        return

    print(f"[recent_form] Detected {max_n} recentForm entries per team in {bronze_table}")

    # ── Build one sub-DataFrame per form index, then union ────────────────
    form_dfs = []
    for i in range(1, max_n + 1):
        form_df = (
            df.select(
                F.get_json_object(F.col("l0payload").cast("string"), "$.teamId")
                 .alias("team_id"),
                F.lit(i).cast("integer").alias("form_order"),
                F.get_json_object(
                    F.col("payload").cast("string"),
                    f"$[0].recentForm{i}._text",
                ).alias("result"),
                F.col("ingested_at"),
                F.col("ingested_from"),
            )
            .filter(F.col("result").isNotNull())
        )
        form_dfs.append(form_df)

    recent_form_df = reduce(lambda a, b: a.union(b), form_dfs)

    # ── Deduplicate: keep latest ingestion per (team_id, form_order) ──────
    window = Window.partitionBy("team_id", "form_order").orderBy(
        F.col("ingested_at").desc()
    )
    recent_form_df = (
        recent_form_df
        .withColumn("_rn", F.row_number().over(window))
        .filter(F.col("_rn") == 1)
        .drop("_rn")
    )

    row_count = recent_form_df.count()
    (
        recent_form_df.write
        .format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(target_table)
    )
    print(f"[recent_form] Written {row_count} rows to {target_table}")


# ── Main config ────────────────────────────────────────────────────────────
LIVE_LADDER_CONFIG = {
    "bronze_table":    "nrl_datalakehouse_prd.bronze_stats.live_ladder",      # ← verify
    "target_prefix":   "nrl_datalakehouse_prd.bronze_stats_flatten.live_ladder",
    "exclude_fields":     set(),
    "flatten_structs":    {},
    "force_array_fields": set(),
    "elements": {
        "ladderposition": "ladderposition",
    },
    "dedup_keys_map": {
        "ladderposition": ["team_id"],
    },
    # Filter to a specific competition/season when those job params are supplied.
    # ingested_from format: liveLadder_{competitionId}_{seasonId}  ← verify prefix
    "source_filter_template": "ingested_from = 'live_ladder_{competition_id}_{season}'",

    "sample_size":    200,
    "type_overrides": {},

    # Post-processing: generate the recentForm child table after the main
    # pipeline writes nrl_live_ladder_ladderposition.
    "post_run_fn": _create_recent_form_table,
}
